FROM tadeorubio/pyodbc-msodbcsql17:latest

# Install additional dependencies
# RUN apt-get update && \
#     apt-get install -y unixodbc-dev && \
#     apt-get install -y gnupg2 && \
#     apt-get clean && \
#     rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip setuptools
RUN pip install pandas pyodbc

# Install ODBC driver for SQL Server
RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - && \
    curl https://packages.microsoft.com/config/debian/10/prod.list > /etc/apt/sources.list.d/mssql-release.list && \
    apt-get update && \
    ACCEPT_EULA=Y apt-get install -y mssql-tools && \
    echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc && \
    /bin/bash -c "source ~/.bashrc"

# Set the working directory
WORKDIR /app

# Copy script files
COPY ./scripts /app/scripts

# Copy data
COPY ./files /app/files

# Set the entry point to run the script
ENTRYPOINT ["python", "/app/scripts/ber_to_sql.py"]
